In [3]:
import pandas as pd

In [4]:
pd.read_csv('C:\Users\HP\Documents\Work 2023\AI Academy\AI Explore\Python\Project\prices.csv')

,Price Dates,Bhindi (Ladies finger),Tomato,Onion,Potato,Brinjal,Garlic,Peas,Methi,Green Chilli,Elephant Yam (Suran)
0,01-01-2023,35.0,18,22.0,20,30,50,25,8,45.0,25
1,02-01-2023,35.0,16,22.0,20,30,55,25,7,40.0,25
2,03-01-2023,35.0,16,21.0,20,30,55,25,7,40.0,25
3,04-01-2023,30.0,16,21.0,22,25,55,25,7,40.0,25
4,08-01-2023,35.0,16,20.0,21,25,55,22,6,35.0,25
5,11-01-2023,35.0,16,18.0,24,25,55,23,6,35.0,30
6,12-01-2023,40.0,16,18.0,22,30,65,23,6,35.0,30
7,15-01-2023,42.0,16,17.0,22,25,65,23,7,35.0,30
8,17-01-2023,35.0,16,18.0,22,30,65,22,10,40.0,35
9,22-01-2023,45.0,16,18.0,22,40,65,25,9,40.0,35
10,23-01-2023,42.0,16,18.0,22,50,65,25,8,40.0,35
11,24-01-2023,45.0,16,16.0,22,60,65,28,15,35.0,30
12,25-01-2023,40.0,16,16.0,20,70,65,25,15,35.0,25
13,27-01-2023,35.0,16,17.0,17,50,65,25,15,35.0,25
14,29-01-2023,35.0,16,15.0,18,40,65,30,15,35.0,25
15,30-01-2023,40.0,16,14.0,17,50,65,30,15,35.0,30
16,31-01-2023,40.0,16,13.5,18,50,65,30,15,35.0,30
17,01-02-2023,42.5,16,13.0,17,50,65,30,12,45.0,30
18,02-02-2023,35.0,16,13.0,17,40,65,30,12,42.0,30
19,03-02-2023,40.0,16,12.5,16,40,65,30,14,40.0,25
20,05-02-2023,38.0,16,12.0,16,50,65,30,12,40.0,25
21,06-02-2023,40.0,16,13.0,16,40,65,35,12,40.0,25
22,07-02-2023,35.0,16,14.0,16,40,65,30,10,50.0,25
23,08-02-2023,40.0,16,14.0,16,40,65,35,10,40.0,25
24,09-02-2023,40.0,16,13.0,16,40,65,30,10,40.0,25
25,10-02-2023,38.0,16,13.0,15,40,65,35,10,40.0,25
26,12-02-2023,45.0,16,13.0,14,45,65,35,8,40.0,25
27,13-02-2023,40.0,16,13.0,14,35,80,35,7,40.0,25
28,14-02-2023,40.0,16,13.0,15,30,80,30,7,40.0,30
29,15-02-2023,40.0,16,12.0,14,30,60,30,6,40.0,30
...,...,...,...,...,...,...,...,...,...,...,...
257,24-11-2023,30.0,16,40.0,20,30,190,40,8,30.0,40
258,26-11-2023,32.0,16,36.0,22,20,230,40,8,30.0,40
259,27-11-2023,32.0,16,37.0,18,25,270,35,8,25.0,25
260,28-11-2023,30.0,16,40.0,18,25,270,35,10,30.0,30
261,29-11-2023,32.0,16,46.0,18,25,270,32,8,30.0,25
262,30-11-2023,30.0,16,50.0,22,25,270,40,7,35.0,30
263,04-12-2023,37.5,16,47.0,18,20,270,40,8,30.0,25
264,05-12-2023,37.0,16,46.0,17,20,270,40,8,25.0,35
265,06-12-2023,37.0,16,47.0,20,30,290,40,7,30.0,40
266,07-12-2023,37.0,16,48.0,18,20,270,40,8,35.0,25
267,08-12-2023,42.5,16,46.0,18,40,270,50,10,30.0,25
268,10-12-2023,42.5,16,48.0,18,35,270,50,10,30.0,25
269,11-12-2023,60.0,16,42.0,22,40,270,40,12,30.0,25
270,12-12-2023,50.0,16,42.0,22,50,270,40,13,35.0,40
271,13-12-2023,50.0,16,40.0,18,45,270,40,12,35.0,40
272,15-12-2023,47.5,16,38.0,22,50,270,35,15,30.0,30
273,17-12-2023,50.0,16,36.0,18,70,270,40,12,40.0,40
274,18-12-2023,50.0,16,30.0,22,60,270,35,25,35.0,25
275,19-12-2023,45.0,16,30.0,22,50,270,30,23,50.0,35
276,20-12-2023,45.0,16,26.0,22,60,270,35,22,30.0,40
277,21-12-2023,50.0,16,28.0,22,70,270,40,20,30.0,30
278,22-12-2023,55.0,16,30.0,20,50,270,40,18,35.0,25
279,24-12-2023,47.5,16,30.0,22,60,270,35,18,30.0,25
280,25-12-2023,45.0,16,24.0,22,70,260,30,18,30.0,25
281,26-12-2023,47.5,16,25.0,22,80,260,30,18,35.0,25
282,27-12-2023,45.0,16,30.0,20,70,260,40,16,40.0,25
283,28-12-2023,45.0,16,30.0,20,70,260,30,20,45.0,25
284,29-12-2023,45.0,16,30.0,22,80,260,30,18,50.0,25
285,31-12-2023,45.0,16,26.0,20,60,250,40,16,50.0,40
286,01-01-2024,45.0,16,9.0,18,50,260,40,15,60.0,25

In [5]:
Vegetable_prices = pd.read_csv('C:\Users\HP\Documents\Work 2023\AI Academy\AI Explore\Python\Project\prices.csv')

In [6]:
Vegetable_prices.head()

,Price Dates,Bhindi (Ladies finger),Tomato,Onion,Potato,Brinjal,Garlic,Peas,Methi,Green Chilli,Elephant Yam (Suran)
0,01-01-2023,35.0,18,22.0,20,30,50,25,8,45.0,25
1,02-01-2023,35.0,16,22.0,20,30,55,25,7,40.0,25
2,03-01-2023,35.0,16,21.0,20,30,55,25,7,40.0,25
3,04-01-2023,30.0,16,21.0,22,25,55,25,7,40.0,25
4,08-01-2023,35.0,16,20.0,21,25,55,22,6,35.0,25

In [20]:
#Convert all data in column 'Price Dates' to Date type.

Price_Date = list(Vegetable_prices['Price Dates']) 

Price_Date = pd.to_datetime(Vegetable_prices["Price Dates"])

In [28]:
#Convert all data in column 'Bhindi (Ladies finger)' to float datatype.

Bhindi_Ladies_Finger = list(Vegetable_prices['Bhindi (Ladies finger)'])

Bhindi_Ladies_Finger = Vegetable_prices['Bhindi (Ladies finger)'].astype(float)

In [32]:
#Convert all data in column 'Tomatoes' to int datatype

Tomatoes = list(Vegetable_prices['Tomato'])

Tomatoes = Vegetable_prices['Tomato'].astype(int)

In [30]:
#Convert all data in column 'Onion' to float datatype.

Onions = list(Vegetable_prices['Onion'])

Onions = Vegetable_prices['Onion'].astype(float)

In [35]:
#Convert all data in column 'Potato' to datatype: int

Potatoes = list(Vegetable_prices['Potato'])

Potatoes = Vegetable_prices['Potato'].astype(int)

In [40]:
#Convert all data in coloumn 'Brinjales' to datatype: int

Brinjales = list(Vegetable_prices['Brinjal'])

Brinjales = Vegetable_prices['Brinjal'].astype(int)

In [42]:
#Convert all data in column 'Garlic' to datatype: int

garlic = list(Vegetable_prices['Garlic'])

garlic = Vegetable_prices['Garlic'].astype(int)

In [44]:
#Convert all data in column 'Peas' to datatype: int

peas = list(Vegetable_prices['Peas'])

peas = Vegetable_prices['Peas'].astype(int)

In [46]:
#Convert all data in column 'Methi' to datatype: int


Methis = list(Vegetable_prices['Methi'])

Methis = Vegetable_prices['Methi'].astype(int)

In [26]:
#Convert all data in column 'Green Chilli' to float type.

Green_Chillis = list(Vegetable_prices['Green Chilli'])

Green_Chillis = Vegetable_prices['Green Chilli'].astype(float)

In [48]:
#Convert all data in column 'Elephant Yam (Suran)' to int data type.

Elephant_Yam_Suran = list (Vegetable_prices['Elephant Yam (Suran)'])

Elephant_Yam_Suran = Vegetable_prices['Elephant Yam (Suran)'].astype(int)